"""FreightWatch ORM models."""

from app.models.base import Base
from app.models.database import (
    Carrier,
    CarrierAlias,
    CitySurcharge,
    ConsultantNote,
    DieselFloater,
    ExtractionCorrection,
    FleetCostProfile,
    FleetDriver,
    FleetVehicle,
    FxRate,
    InvoiceDisputeEvent,
    # Invoice
    InvoiceHeader,
    InvoiceLine,
    LsvaRate,
    LsvaTable,
    ManualMapping,
    MautRate,
    MautTable,
    MautZoneMap,
    OwnTour,
    OwnTourStop,
    # Parsing
    ParsingTemplate,
    # Project
    Project,
    RawExtraction,
    Report,
    # Shipment
    Shipment,
    ShipmentBenchmark,
    TariffFtlRate,
    TariffNebenkosten,
    TariffRate,
    TariffSpecialCondition,
    TariffSurcharge,
    # Tariff
    TariffTable,
    TariffZoneMap,
    # Core
    Tenant,
    Upload,
    User,
    # Fleet
    Vehicle,
)

__all__ = [
    "Base",
    "Tenant",
    "Carrier",
    "CarrierAlias",
    "Upload",
    "FxRate",
    "User",
    "Project",
    "ConsultantNote",
    "Report",
    "TariffTable",
    "TariffRate",
    "TariffZoneMap",
    "TariffNebenkosten",
    "TariffSurcharge",
    "TariffSpecialCondition",
    "TariffFtlRate",
    "DieselFloater",
    "MautTable",
    "MautRate",
    "MautZoneMap",
    "LsvaTable",
    "LsvaRate",
    "CitySurcharge",
    "InvoiceHeader",
    "InvoiceLine",
    "InvoiceDisputeEvent",
    "Shipment",
    "ShipmentBenchmark",
    "Vehicle",
    "FleetCostProfile",
    "OwnTour",
    "OwnTourStop",
    "FleetVehicle",
    "FleetDriver",
    "ParsingTemplate",
    "ManualMapping",
    "RawExtraction",
    "ExtractionCorrection",
]
